import { ProductInfo } from "@/types/global";
export const data: ProductInfo[] = [
  {
    unavailable: false,
    linkTo: "/bathroom/intelligent/one-c-plus",
    id: 1,
    sku: "E414-02",
    collection: null,
    category: "intelligent",
    name: "AXENT.ONE C PLUS Intelligent Toilet",
    aliases: "one-c-plus",
    subtitle: "Ingelligent toilet with KIRIN Flush System",
    details:
      "The AXENT.ONE C+ intelligent toilet refines intuitive design and adaptable technology. This award-winning intelligent toilet is equipped with the latest smart-ware technology customize your AXENT.ONE C+ functions with the swipe of a sensor or click of a button. The AXENT.ONE C+ is paired with the Kirin flushing system. This tankless design and powerful flushing efficiency lends to the AXENT.ONE C+ one-of-a-kind water conservation benefits.",
    features: {
      dimensions: "L 28 1/2” x W 15 7/8” x H 19 1/4”",
      weight: "110 lbs",
      material: "Vitreous China & Polypropylene Seat",
      color: "White",
      water: "1.0 GPF (3.8 LPF)",
    },
    configuration: {
      outlook: [
        "Customizable Integrated Bidet Seat",
        "Floor mounted/ Siphonic",
        '12" Rough In',
        "Elongated Bowl Shape",
        "ADA Height Toilet Bowl",
      ],
      watertank: [
        "Kirin Flush System",
        "Patented Tankless Technology",
        "Manual and Remote Activated Flushing",
        "Smart Phone App Enabled Control",
      ],
      cleaning: [
        "Deodorizer",
        "Warm Air Dryer",
        "Instantly Warm Water Temperature",
        "Adjustable Shower Flow and Masaging",
      ],
      seatlid: [
        "Adjustable Self-Warming Seat",
        "Automated Hands-Free, Soft-Closing Seat and Lid",
        "Easy Clean Antibacterial Coating",
        "Night Light",
        "Rimless Flush",
        "1000 Gram Miso Score",
        "Stainless Steel Wand",
        "User Profiles",
      ],
    },
    imgSrc: "/products_img/one-c-plus-p.png",
    imgAlt: "one-c-plus",
    coverSrc: "/products_img/one-c-plus-sq.png",
    sketchImg: [
      "/products_img/one-c-plus-s-1.png",
      "/products_img/one-c-plus-s-2.png",
    ],
    specification: "/docs/one-c-plus_spec.pdf",
    manual: "/docs/one-c-plus_manual.pdf",
    install: "/docs/one-c-plus_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/intelligent/one-plus",
    id: 2,
    sku: "E310-E291-U1",
    collection: null,
    category: "intelligent",
    name: "AXENT.ONE PLUS Intelligent Toilet",
    aliases: "one-plus",
    subtitle: "Ingelligent toilet with KIRIN Flush System",
    details:
      "Inspired by our success and lessons learned in Europe and Asia\\’s notoriously condensed urban environments, we\\’re introducing North America\\’s most intuitive and space-saving toilet \\– the AXENT.ONE Plus wall-hung intelligent toilet.",
    features: {
      dimensions: "L 23.35” x W 14.57” x H 15.63”",
      weight: "88.2lbs",
      material: "Vitreous China and Polypropylene Seat",
      color: "White",
      water: "Dual Flush Capability",
    },
    configuration: {
      outlook: [
        "Customizable Integrated Bidet Seat",
        "Intuitive Night Light",
        "Elongated Bowl Shape",
        "ADA Height Toilet Bowl",
      ],
      watertank: ["Manual Activated Flushing", "Rimless Flush Design"],
      cleaning: [
        "Deodorizer",
        "Warm Air Dryer",
        "Instantly Warm Water Temperature",
        "Adjustable Shower Flow and Masaging",
      ],
      seatlid: [
        "Adjustable Self-Warming Seat",
        "Easy Clean Antibacterial Coating",
        "Remote Control",
        "App Controlled",
        "User Profiles",
      ],
    },
    imgSrc: "/products_img/one-plus-p.png",
    imgAlt: "one-plus",
    coverSrc: "/products_img/one-plus-sq.png",
    sketchImg: [
      "/products_img/one-plus-s-1.png",
      "/products_img/one-plus-s-2.png",
      "/products_img/one-plus-s-3.png",
      "/products_img/one-plus-s-4.png",
    ],
    specification: "/docs/one-c-plus_spec.pdf",
    manual: "/docs/one-c-plus_manual.pdf",
    install: "/docs/one-plus_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/intelligent/milton",
    id: 3,
    sku: "E001-0201-U1",
    collection: null,
    category: "parts",
    name: "MILTON Intelligent Toilet Seat",
    aliases: "milton",
    subtitle: "Intelligent Technology for 180° Degrees of Clean",
    details:
      "The Milton intelligent bidet seat offers fully customizable rear and front cleansing options. Additional oscillating, pulsating massage and aerated bubbly water infusion technology are just a few of the customizable features you can personalize and program into your Milton intelligent bidet.",
    features: {
      dimensions: "L 19-7/16” x W 15” x H 5-3/4”",
      weight: "17.7lbs",
      material: "Polypropylene",
      color: "White",
      water: null,
    },
    configuration: {
      outlook: [
        "Customizable Integrated Bidet Seat",
        "Intuitive Night Light",
        "Elongated Bowl Shape",
      ],
      watertank: [],
      cleaning: [
        "Deodorizer",
        "Warm Air Dryer",
        "Instantly Warm Water Temperature",
        "Adjustable Shower Flow and Masaging",
      ],
      seatlid: [
        "Adjustable Self-Warming Seat",
        "Remote Control",
        "Stainless Steel Wand",
        "User Profiles",
      ],
    },
    imgSrc: "/products_img/milton-p.png",
    imgAlt: "milton seat",
    coverSrc: "/products_img/milton-sq.png",
    sketchImg: [
      "/products_img/milton-s-1.png",
      "/products_img/milton-s-2.png",
      "/products_img/milton-s-3.png",
      "/products_img/milton-s-4.png",
    ],
    specification: "/docs/milton_spec.pdf",
    manual: "/docs/milton_manual.pdf",
    install: "/docs/milton_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/parts/electric-seat",
    id: 4,
    sku: "FE105 (U-Shaped)",
    collection: null,
    category: "parts",
    name: "SLIMS U Shaped Electric Bidet Seat",
    aliases: "electric-seat",
    subtitle: "INTELLIGENT E-BIDET SEAT",
    details:
      "All of the cleansing benefits of an intelligent toilet in a convenient and compact intelligent bidet seat design. The U/V-Shape intelligent bidet seat offers instant seat and water warming, a luxurious and adjustable cleansing shower spray, and a soft-closing seat all in a low-profile and minimalistic style. The gentle showering function can be customized with the turn of a conveniently located dial.",
    features: {
      dimensions: "L 20-1/5” x W 14-4/5” x H 3-3/4”",
      weight: "7.75lbs",
      material: "Polypropylene",
      color: "White",
      water: "20-100psi",
    },
    imgSrc: "/products_img/electric-seat-u.png",
    imgAlt: "U/V Shape Electric Bidet Seat",
    coverSrc: "/products_img/electric-seat-sq.png",
    sketchImg: [
      "/products_img/electric-seat-s-1.png",
      "/products_img/electric-seat-s-2.png",
      "/products_img/electric-seat-s-3.png",
    ],
    specification: "/docs/electric-seat-FE105_spec.pdf",
    manual: "/docs/electric-seat_manual.pdf",
    install: "",
  },
  {
    unavailable: true,
    linkTo: "/bathroom/intelligent/infinity",

    id: 5,
    sku: "coming soon",
    collection: "axent.one",
    category: "intelligent",
    name: "AXENT.INFINITY Intelligent Toilet",
    aliases: "infinity",
    subtitle: "Kirin Flush: Ultimate Assurance in All-round Performance",
    details:
      "The revolutionary Kirin Pressure-assisted Flush System adopts cutting-edge technology that redefines global standards. By harnessing air energy, it achieves double-low net flushing with triple cleanliness, freeing the user from any flushing anxiety. The ONE.DIAL and small remote controller offer peace of mind at all times.",
    features: {
      dimensions: "L 28 ½” x W 15 7/8” x H 19 ¼”",
      weight: "110 lbs",
      material: "Vitreous China and Polypropylene Seat",
      color: "White/Matte Black, White/ Matte Gold",
      water: "1.0 GPF (3.8LPF)",
    },
    configuration: {
      outlook: [
        "Smart Temperature Sensing System",
        "Full-process Smart Sensing, Convenience for All",
        "Nozzle UV Sterilization Technology",
        "Versatile Control Options",
        "Intelligent Night Light",
      ],
      watertank: [
        "Bubble Care for Cleanness and Comfort",
        "Antibacterial Seat",
      ],
      cleaning: ["Men's Auto Flush", "Warm Air Dryer"],
      seatlid: [
        "Soft-close Lid and Seat",
        "Stainless Steel Wand",
        "Mechanical Flush",
        "App Control",
        "Remote Control",
        "Auto Open Seat",
        "Rimless Flush",
        "Massage Modes",
        "User Profiles",
        "Easy Clean Glaze",
        "ADA Height Bowl",
      ],
    },
    imgSrc: "/products_img/infinity-black.jpg",
    imgAlt: "infinity",
    coverSrc: "/products_img/infinity-sq.png",
    sketchImg: [
      "/products_img/electric-seat-s-1.png",
      "/products_img/electric-seat-s-2.png",
      "/products_img/electric-seat-s-3.png",
    ],
    specification: "",
    manual: "",
    install: "",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/novia",

    id: 6,
    sku: "",
    collection: "novia",
    category: "novia",
    name: "NOVIA",
    aliases: "novia",
    subtitle: "",
    details: "",
    features: {
      dimensions: "L 20-1/5” x W 14-4/5” x H 3-3/4”",
      weight: "7.75lbs",
      material: "Polypropylene",
      color: "White",
      water: "20-100psi",
    },
    imgSrc: "/products_img/novia-white.jpg",
    imgAlt: "novia",
    coverSrc: "/products_img/novia-cover.jpg",
    sketchImg: [
      "/products_img/electric-seat-s-1.png",
      "/products_img/electric-seat-s-2.png",
      "/products_img/electric-seat-s-3.png",
    ],
    specification: "",
    manual: "",
    install: "",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/regular/primus",
    id: 7,
    sku: "W431-04",
    collection: null,
    category: "regular",
    name: "Primus Tankless Toilet",
    aliases: "primus",
    subtitle: "Minimalist Lifestyle with Kirin Flush",
    details:
      "Adopting an aesthetically pleasing streamlined design and a sleek flat white exterior, it aligns with modern home aesthetics. The efficient Kirin Flush System ensures pristine cleanliness after every use, offering the enjoyment of a comfortable life.",
    features: {
      dimensions: "L 28-1/2” x W 15” x H 19-5/16”",
      weight: "110lbs",
      material: "Vitreous China and Polypropylene Seat",
      color:
        "White with Space Silver Trim (ALT: Champagne Gold, Rose Gold, White, and Matte Black Trims (SOLD SEPARATELY)",
      water: "Single Flush 1.0 GPF(3.8LPF)",
    },
    configuration: {
      outlook: ["streamlined design and a sleek flat white exterior"],
      watertank: ["Kirin Flush System"],
      cleaning: [
        "easy clean glaze technology",
        "entire Trap-way are coated with a smooth glaze",
        "ADA Height",
      ],
      seatlid: ["antibacterial material", "Soft Close seat & lid"],
    },
    imgSrc: "/products_img/primus-sliver.jpg",
    imgAlt: "primus",
    coverSrc: "/products_img/primus-sq.png",
    sketchImg: [
      "/products_img/primus-s-1.png",
      "/products_img/primus-s-2.png",
      "/products_img/primus-s-3.png",
    ],
    specification: "/docs/primus_spec.pdf",
    manual: "/docs/primus_manual.pdf",
    install: "/docs/primus_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/regular/peninsula",
    id: 8,
    sku: "W532-2020",
    collection: null,
    category: "regular",
    name: "PENINSULA Two Piece Toilet",
    aliases: "peninsula",
    subtitle: "Two-Piece Toilet",
    details:
      "The Peninsula Toilet features elegant curves while conveying a charming traditional frankness. Our Peninsula Close Coupled Toilet is equipped with a bottom inlet,vertical outlet, 1.28 GPF (4.8 L) flush, Easy Clean antibacterial glaze, a silent seat and a 12” rough-in dimension.",
    features: {
      dimensions: "L 28 3/16” x W 17 3/4” x H 31 1/4”",
      weight: "82.9lbs",
      material: "Vitreous China and Polypropylene Seat",
      color: "White/ Chrome",
      water: "Single Flush 1.28GPF(4.8L)",
    },
    configuration: {
      outlook: [
        "Rough-In 12",
        "Floor Mounted/Siphonic",
        "Elongated Bowl Shape",
        "ADA Height Toilet Bowl",
      ],
      watertank: [
        "Tank Lever:B5081.PC",
        "Left-sided Handle Lever/ Polished Chrome Bras",
        "Soft Close Seat",
        "Easy Clean Glaze",
      ],
    },
    imgSrc: "/products_img/peninsula-p.png",
    imgAlt: "peninsula",
    coverSrc: "/products_img/peninsula-sq.png",
    sketchImg: [
      "/products_img/peninsula-s-1.png",
      "/products_img/peninsula-s-2.png",
      "/products_img/peninsula-s-3.png",
    ],
    specification: "/docs/peninsula_spec.pdf",
    manual: "",
    install: "/docs/peninsula_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/regular/alton",
    id: 9,
    sku: "W375-2020",
    collection: null,
    category: "regular",
    name: "ALTON One Piece Toilet",
    aliases: "alton",
    subtitle: "ONE-PIECE TOILET",
    details:
      "Rich with soft angles and full curves, the Alton Toilet epitomizes a balanced union between modern and classic design. The Alton One-Piece Toilet includes 3” flapper with increased head pressure, a bottom inlet with a vertical outlet, a 1.28 GPF (4.8 L) flush, a 12” rough-in and is protected with an Easy Clean glaze for easy lifetime maintenance.",
    features: {
      dimensions: "L 27 11/16” x W 14 7/16” x H 28 3/8”",
      weight: "90.4 lbs",
      material: "Vitreous China, Polypropylene Seat",
      color: "White and Chrome",
      water: "Single Flush 1.28GPF(4.8L)",
    },
    configuration: {
      outlook: [
        "Rough-In 12",
        "Floor Mounted/Siphonic",
        "Elongated Bowl Shape",
        "ADA Height Toilet Bowl",
        "One Piece Toilet",
        "Soft Close Lift Off Seat",
      ],
    },
    imgSrc: "/products_img/alton-p.jpg",
    imgAlt: "alton",
    coverSrc: "/products_img/alton-sq.png",
    sketchImg: [
      "/products_img/alton-s-1.png",
      "/products_img/alton-s-2.png",
      "/products_img/alton-s-3.png",
    ],
    specification: "/docs/alton_spec.pdf",
    manual: "",
    install: "/docs/alton_install.pdf",
  },
  {
    unavailable: true,
    linkTo: "/bathroom/regular/stella",

    id: 10,
    sku: "W320-1131-U1",
    collection: null,
    category: "regular",
    name: "REGATTA One Piece Skirted Toilet",
    aliases: "stella",
    subtitle: "Elegantly Practical, Seamlessly Perfect",
    details:
      "The oval curves create a fashionable sense of aesthetics, while the white glaze exudes a refreshing elegance. High-quality ceramic, paired with the Kirin Pressure-assisted Flush System, creates a pristine bathroom environment.",
    features: {
      dimensions: "L 28.93” x W 17.40”x H 20.47”",
      weight: "110 LBS",
      material: "Vitreous China & Polypropylene Seat",
      color: "White",
      water: "1.0 GPF / 3.8LPF",
    },
    configuration: {
      outlook: [
        "Antibacterial Easy-to-clean Glaze",
        "ADA Height",
        "12” Rough In",
      ],
      watertank: ["Kirin Pressure-assisted Flush System"],
      cleaning: ["Entire Trapway Glazing"],
      seatlid: [
        "Comfortable Antibacterial Seat",
        "Soft Close Lift Off Seat",
        "Rimless Flush",
      ],
    },
    sketchImg: [
      "/products_img/stella-s-1.png",
      "/products_img/stella-s-2.png",
      "/products_img/stella-s-3.png",
    ],
    imgSrc: "/products_img/stella-p.jpg",
    imgAlt: "stella",
    coverSrc: "/products_img/stella-sq.png",
    specification: "",
    manual: "",
    install: "",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/basin/one-square",
    id: 11,
    sku: "L316-1101-U1",
    collection: null,
    category: "basin",
    name: "AXENT.ONE C Above Counter Basin",
    aliases: "one-square",
    subtitle: "Counter Top WashBasin",
    details:
      "This basin features beautiful structure, gracious shapes and elegant, thin edges. A masterpiece of craftsmanship, features no tap hole and an easy clean glaze for easy lifetime maintenance.",
    features: {
      dimensions: "L 17 3/4” x W 17 3/4” x H 5 1/4”",
      weight: "25.4lbs",
      material: "Fine Fire Clay(FFC)",
      color: "White",
    },
    imgSrc: "/products_img/one-square-p.png",
    imgAlt: "one-square",
    coverSrc: "/products_img/one-square-p.png",
    sketchImg: [
      "/products_img/one-square-s-1.png",
      "/products_img/one-square-s-2.png",
      "/products_img/one-square-s-3.png",
    ],
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "/docs/one-square_spec.pdf",
    manual: "",
    install: "/docs/one-square_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/basin/one-round",
    id: 12,
    sku: "L310-1101-U1",
    collection: null,
    category: "basin",
    name: "AXENT.ONE C Above Counter Basin",
    aliases: "one-round",
    subtitle: "Counter Top WashBasin",
    details:
      "This basin features beautiful structure, gracious shapes and elegant, thin edges. A masterpiece of craftsmanship, features no tap hole and an easy clean glaze for easy lifetime maintenance.",
    features: {
      dimensions: "L 17 3/4” x H 5 1/4”",
      weight: "22.5lbs",
      material: "Fine Fire Clay(FFC)",
      color: "White",
    },
    imgSrc: "/products_img/one-round-p.png",
    imgAlt: "one-round",
    coverSrc: "/products_img/one-round-p.png",
    sketchImg: [
      "/products_img/one-round-s-1.png",
      "/products_img/one-round-s-2.png",
    ],
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "/docs/one-round_spec.pdf",
    manual: "",
    install: "/docs/one-round_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/basin/one-rect",
    id: 13,
    sku: "L017-4101-U1",
    collection: null,
    category: "basin",
    name: "AXENT.ONE C Under Counter Basin",
    aliases: "one-rect",
    subtitle: "Under Counter WashBasin",
    details:
      "This basin features beautiful structure, gracious shapes and elegant, thin edges. A masterpiece of craftsmanship, features no tap hole and an easy clean glaze for easy lifetime maintenance.",
    features: {
      dimensions: "L 23 5/8” x W 17 1/2” D 7 7/8”",
      weight: "29.1lbs",
      material: "Vitreous China",
      color: "White",
    },
    imgSrc: "/products_img/one-rect-p.png",
    imgAlt: "one-rect",
    coverSrc: "/products_img/one-rect-p.png",
    sketchImg: [
      "/products_img/one-rect-s-1.png",
      "/products_img/one-rect-s-2.png",
      "/products_img/one-rect-s-3.png",
    ],
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "/docs/one-rect_spec.pdf",
    manual: "",
    install: "/docs/one-rect_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/basin/annie",
    id: 14,
    sku: "L370-1101-U1",
    collection: null,
    category: "basin",
    name: "Annie",
    aliases: "annie",
    subtitle: "Counter Top Basin",
    details:
      "The Annie Counter Top Basin comes with overflow hole, without tap hole and with Easy Clean glaze that makes cleaning a breeze.",
    features: {
      dimensions: "L 21 9/16” x W 14 7/8” H 6 15/16”",
      weight: "22lbs",
      material: "Vitreous China",
      color: "White",
    },
    imgSrc: "/products_img/annie-p.png",
    imgAlt: "annie",
    coverSrc: "/products_img/annie-p.png",
    sketchImg: [
      "/products_img/annie-s-1.png",
      "/products_img/annie-s-2.png",
      "/products_img/annie-s-3.png",
    ],
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "/docs/annie_spec.pdf",
    manual: "",
    install: "/docs/annie_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/parts/bidet-seat-fb106",
    id: 15,
    sku: "FB106",
    collection: null,
    category: "parts",
    name: "TELESCOPING ELONGATED BIDET SEAT",
    aliases: "bidet-seat",
    subtitle: "with V-shape and U-shape options",
    details:
      "This powerless bidet seat offers luxurious rear and front washing, gentle massaging, a soft/slow-closing seat and lid, the highest quality antibacterial nozzle and easy function management without any need for electricity. You can conveniently adjust the water flow of the shower to your preference(s) with the easy adjustment of a conveniently located side dial. And for extra convenient cleaning, the seat and lid are easily removed within seconds.",
    features: {
      dimensions: "L 18 11/16” x W 14 9/16” H 2 7/16”",
      weight: "6.4lbs",
      material: "Polypropylene",
      color: "White",
    },
    imgSrc: "/products_img/bidet-seat-p.jpg",
    imgAlt: "bidet-seat",
    coverSrc: "/products_img/bidet-seat-sq.png",
    sketchImg: [
      "/products_img/bidet-seat-s-1.png",
      "/products_img/bidet-seat-s-2.png",
      "/products_img/bidet-seat-s-3.png",
    ],
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "/docs/bidet-seat-FB106_spec.pdf",
    manual: "/docs/bidet-seat-FB106_manual.pdf",
    install: "",
  },
  {
    unavailable: true,
    linkTo: "/bathroom/regular/studio",
    id: 16,
    sku: "W390-2025",
    collection: null,
    category: "regular",
    name: "STUDIO One Piece Skirted Toilet",
    aliases: "reuss",
    subtitle: "ONE PIECE SKIRTED TOILET",
    details:
      "Rich with soft angles and full curves, the Studio Toilet epitomizes a balanced union between modern and classic design. The Studio One-Piece Skirted Toilet includes a rimless flush design, a bottom inlet with a vertical outlet, a 1.28 GPF (4.8L) flush, 12” rough-in and is protected with an Easy Clean glaze for easy lifetime maintenance.",
    features: {
      dimensions: "L29 1/2” * W 17” * H 27 3/4”",
      weight: "103lbs",
      material: "Vitreous China, Polypropylene Seat",
      color: "White / Chrome",
      water: "Single Flush 1.28 GPF (4.8L)",
    },
    configuration: {
      outlook: [
        "12” Rough In",
        "Floor mounted/Siphonic",
        "Elongated Bowl Shape",
        "ADA Height Toilet Bowl",
      ],
      watertank: ["Rimles flush design", "U Shaped Bowl", "Soft Close Seat"],
    },
    imgSrc: "/products_img/reuss-sq.png",
    imgAlt: "reuss toilet",
    coverSrc: "/products_img/reuss-sq.png",
    sketchImg: [
      "/products_img/reuss-s-1.png",
      "/products_img/reuss-s-2.png",
      "/products_img/reuss-s-3.png",
    ],
    specification: "/docs/reuss_spec.pdf",
    manual: "",
    install: "/docs/reuss_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/parts/primus-color-strip",
    id: 17,
    sku: "W330-D003-U1, W330-D004-U1, W330-D005-U1, W330-D006-U1",
    collection: null,
    category: "",
    name: "Color Strip for Primus",
    aliases: "primus-color-strip",
    subtitle: "Multiple Color Options",
    details:
      "Embracing a diverse array of colors can significantly enhance the enjoyment and vibrancy of any experience. ",
    features: {
      material: "VC ceramics, PP cover",
      color:
        "space silver, Champagne Gold, Rose Gold, White, Matt Black, Meteorite Grey",
    },
    sketchImg: [],
    imgSrc: "/products_img/primus-color-strip-rose.png",
    imgAlt: "primus-color-strip",
    coverSrc: "/products_img/primus-color-strip-gold.png",
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "",
    manual: "",
    install: "",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/mint/mint-one",
    id: 18,
    sku: "TS026-3",
    collection: "mint",
    category: "intelligent",
    name: "Mint One Intelligent Toilet",
    aliases: "mint-one",
    subtitle: "Reshaping the Future of Intelligent Toilets",
    details:
      " The MINT.ONE inteligent toilet redfines intuitive design and adaptable technology. This award-winning intelligent toilet is equipped with the latest smartware technology customize your MINT.ONE functions with the swipe of a sensoror click of abuton",
    features: {
      dimensions: "L 26 3/4” x W 15 1/4” x H 19 1/4”",
      weight: "100 lbs",
      material: "Vitreous China and Polypropylene Sea",
      color: "White and Chrome Trim",
      water: "Single Flush 1.0GPF(3.8LPF)",
    },
    configuration: {
      outlook: [
        "Customizable Integrated Bidet Seat",
        "Floor mounted/ Siphonic",
        '12" Rough In',
        "Elongated Bowl Shape",
        "Patented Tankles Technology",
      ],
      watertank: [
        "Kirin Flush System",
        "Patented Tankless Technology",
        "Manual and Remote Activated Flushing",
        "Smart Phone App Enabled Control",
      ],
      cleaning: [
        "Deodorizer",
        "Warm Air Dryer",
        "Instantly Warm Water Temperature",
        "Adjustable Shower Flow and Masaging",
      ],
      seatlid: [
        "Adjustable Self-Warming Seat",
        "Automated Hands-Free, Soft-Closing Seat and Lid",
        "Easy Clean Antibacterial Coating",
        "Rimless Flush",
        "Remote Control",
        "Massage Modes",
        "Night Light",
      ],
    },
    imgSrc: "/products_img/mint-one-p.png",
    imgAlt: "mint-one-1",
    coverSrc: "/products_img/mint-one-sq.png",
    sketchImg: [
      "/products_img/mint-one-s-1.png",
      "/products_img/mint-one-s-2.png",
      "/products_img/mint-one-s-3.png",
    ],
    specification: "/docs/mint-one_spec.pdf",
    manual: "/docs/mint-one_manual.pdf",
    install: "/docs/mint-one_install.pdf",
  },
  {
    unavailable: true,
    linkTo: "/bathroom/mint/mint-two",
    id: 19,
    sku: " TS036-3-BK (White/Black); TS036-3-WT (All White)",
    collection: "mint",
    category: "intelligent",
    name: "Mint Two Intelligent Toilet",
    aliases: "mint-two",
    subtitle: "Smarter and Sexier",
    details:
      "A perfect blend of elegance and efficiency where functionality intertwines with asethetic grace.",
    features: {
      dimensions: "L 26 3/4” x W 15 1/4” x H 19 1/4”",
      weight: "100 lbs",
      material: "Vitreous China and Polypropylene Seat",
      color: "White and White/Black",
      water: "Single Flush 1.0GPF(3.8LPF)",
    },
    configuration: {
      outlook: ['12" Rough In'],
      watertank: [
        "Kirin Pressure-assisted Flush Technology",
        "Manual and Remote Activated Flushing",
        "Smart Phone App Enabled Control",
      ],
      cleaning: [
        "Upgrade of Foam Guard Black Technology",
        "Intelligent Control System",
      ],
      seatlid: [
        "Automated Hands-Free, Soft-Closing Seat and Lid",
        "Easy Clean Antibacterial Coating",
        "Remote Control ",
        "Rimless Flush",
        "Massage Modes",
        "Stainless Steel Wand",
        "Instant Warm Water",
        "Night Light",
        "Warm Air Dryer",
        "Deodorizer",
        "LED Temperature Display",
      ],
    },
    imgSrc: "/products_img/mint-two-BK.png",
    imgAlt: "mint-two",
    coverSrc: "/products_img/mint-two-sq.png",
    sketchImg: [
      "/products_img/mint-two-s-1.png",
      "/products_img/mint-two-s-2.png",
      "/products_img/mint-two-s-3.png",
    ],
    specification: "/docs/mint-spec.pdf",
    manual: "/docs/mint-two_manual.pdf",
    install: "/docs/mint-two_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/mint/batik",
    id: 20,
    sku: "SKU: T0151 (51” Bathtub), T0159 (59” Bathtub), T0167 (67” Bathtub)",
    collection: "mint",
    category: "tub",
    name: "Batik Bathtub",
    aliases: "batik",
    subtitle: "Elegant Simplicity, Tailored to Your Taste",
    details:
      "The bathtub boasts a plump and rounded silhouette, exuding elegance and grandeur. The ultra-thin edge of the bathtub adds to its aesthetic appeal, creating a more spacious and airy ambiance.",
    features: {
      dimensions: "52.8Gal, 55.5Gal, 66Gal",
      capacity: "52.8 GAL (T0151),  55.5 GAL (T0159), 66 GAL (T0167)",
      material: "Acrylic",
      color: "Coming Soon",
      overFlow: "Yes/ White",
      drainageMode: "Flip-over type/ White",
    },
    configuration: {
      outlook: [
        "Indulgent Soaking, Tailored to Your Desire",
        "Durability, Skin-friendliness",
        "Long-lasting Warmth Retention",
      ],
    },
    imgSrc: "/products_img/batik-p.png",
    imgAlt: "batik tub",
    coverSrc: "/products_img/batik-sq.png",
    sketchImg: [
      "/products_img/batik-s-1.png",
      "/products_img/batik-s-2.png",
      "/products_img/batik-s-3.png",
    ],
    specification: "/docs/batik_manual.pdf",
    manual: "/docs/batik_manual.pdf",
    install: "/docs/batik_install.pdf",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/mint/rina",
    id: 21,
    sku: "T0151, T0159, T0167",
    collection: "mint",
    category: "mint",
    name: "RINA LUXURY",
    aliases: "rina",
    subtitle: "Purified Water Nourishing Beauty and Revitalizing Skin",
    details:
      "Embedded within the shower head, the filter is rich in Vitamin C, effectively neutralizing chlorine in tap water to purify and protect every inch of your skin. The scientific blend of Vitamin C in the filter and hyaluronic acid, known as the Hydration Bomb, enhances skin's antioxidant capacity and moisture retention, rescuing parched skin and leaving it bouncy and vibrant.",
    features: {
      dimensions: '10.24" *  4.72" * 1.97"',
      weight: "?",
      material: "?",
      color: "Icy Moldy Pink, Fine Floral White, Mocha Beige, Ice Crystal Blue",
    },
    configuration: {
      outlook: [
        "Bubble Water",
        "VC Nutrient Solution",
        "Fragrance Essential Oil",
        "Skin-refreshing Micro-bubble Water For a Deep Cleanse",
        "Unleashing the Essence of Vitamin C Healthy Skin Begins with Your Bath",
        "Switching Seamlessly Among Three Splash",
      ],
    },
    imgSrc: "/products_img/rina-4-color.png",
    imgAlt: "rina shower head",
    coverSrc: "/products_img/rina-1.png",
    sketchImg: ["/products_img/rina-s-1.png", "/products_img/rina-s-2.png"],
    specification: "",
    manual: "",
    install: "",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/parts/bidet-seat-fb107",
    id: 22,
    sku: "FB107",
    collection: null,
    category: "parts",
    name: "TRADITIONAL ELONGATED BIDET SEAT",
    aliases: "bidet-seat",
    subtitle: "with V-shape and U-shape options",
    details:
      "This powerless bidet seat features rear wash, front wash, slow closing and an antibacterial nozzle – and it functions completely without electricity. Controlled by a discrete side knob, you can conveniently adjust the water flow to your preference(s). And for extra convenient cleaning, the seat and lid are easily removed within seconds.",
    features: {
      dimensions: "L 17 14/16” x W 14 9/16” H 2 7/16”",
      weight: "6.4lbs",
      material: "Polypropylene",
      color: "White",
    },
    imgSrc: "/products_img/bidet-seat-fb107.png",
    imgAlt: "bidet-seat",
    coverSrc: "/products_img/bidet-seat-fb107.png",
    sketchImg: [
      "/products_img/bidet-seat-fb107-s-1.png",
      "/products_img/bidet-seat-fb107-s-2.png",
      "/products_img/bidet-seat-fb107-s-3.png",
    ],
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "/docs/bidet-seat-FB107_spec.pdf",
    manual: "/docs/bidet-seat-FB107_manual.pdf",
    install: "",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/parts/bidet-seat-fb108",
    id: 23,
    sku: "FB108",
    collection: null,
    category: "parts",
    name: "ROUND FRONT BIDET SEAT",
    aliases: "bidet-seat",
    subtitle: "with V-shape and U-shape options",
    details:
      "This powerless bidet seat features rear wash, front wash, slow closing and an antibacterial nozzle – and it functions completely without electricity. Controlled by a discrete side knob, you can conveniently adjust the water flow to your preference(s). And for extra convenient cleaning, the seat and lid are easily removed within seconds.",
    features: {
      dimensions: "L 17 14/16” x W 14 9/16” H 2 7/16”",
      weight: "6.2lbs",
      material: "Polypropylene",
      color: "White",
    },
    imgSrc: "/products_img/bidet-seat-fb108.png",
    imgAlt: "bidet-seat",
    coverSrc: "/products_img/bidet-seat-fb108.png",
    sketchImg: [
      "/products_img/bidet-seat-fb108-s-1.png",
      "/products_img/bidet-seat-fb108-s-2.png",
      "/products_img/bidet-seat-fb108-s-3.png",
    ],
    configuration: {
      outlook: [],
      watertank: [],
      cleaning: [],
      seatlid: [],
    },
    specification: "/docs/bidet-seat-FB108_spec.pdf",
    manual: "/docs/bidet-seat-FB108_manual.pdf",
    install: "",
  },
  {
    unavailable: false,
    linkTo: "/bathroom/intelligent/electric-seat",
    id: 24,
    sku: "FE106",
    collection: null,
    category: "parts",
    name: "LITE V Shaped Electric Bidet Seat",
    aliases: "electric-seat",
    subtitle: "INTELLIGENT E-BIDET SEAT",
    details:
      "All of the cleansing benefits of an intelligent toilet in a convenient and compact intelligent bidet seat design. The V-Shape intelligent bidet seat offers instant seat and water warming, a luxurious and adjustable cleansing shower spray, and a soft-closing seat all in a low-profile and minimalistic style. The gentle showering function can be customized with the turn of a conveniently located dial.",
    features: {
      dimensions: "L 20-1/5” x W 14-4/5” x H 3-3/4”",
      weight: "7.75lbs",
      material: "Polypropylene",
      color: "White",
      water: "20-100psi",
    },
    imgSrc: "/products_img/electric-seat-u.png",
    imgAlt: "U/V Shape Electric Bidet Seat",
    coverSrc: "/products_img/electric-seat-sq.png",
    sketchImg: [
      "/products_img/electric-seat-s-1.png",
      "/products_img/electric-seat-s-2.png",
      "/products_img/electric-seat-s-3.png",
    ],
    specification: "/docs/electric-seat-FE106_spec.pdf",
    manual: "/docs/electric-seat_manual.pdf",
    install: "",
  },
  // {
  //   id: 22,
  //   sku: "unknow",
  //   collection: "meta",
  //   category: "intelligent",
  //   name: "META",
  //   aliases: "meta",
  //   subtitle: "coming soon...",
  //   details: "coming soon...",

  //   features: {
  //     dimensions: " ",
  //     weight: " ",
  //     material: " ",
  //     color: " ",
  //     water: " ",
  //   },
  //   imgSrc: "/products_img/meta-1.jpg",
  //   imgAlt: "meta",
  //   coverSrc: "/products_img/meta-cover.png",
  //   sketchImg: [],
  //   specification: null,
  //   manual: null,
  // },
];
