import { RefInfo } from "@/types/global";
export const refData: RefInfo[] = [
  {
    imgsrc: ["/reference_img/farmer-hotel-basedow_1.jpg"],
    title: "Farmer Hotel Basedow",
    location: "Mecklenburg-Vorpommern, Germany",
    description:
      "Each of the Farmer Hotel Basedow’s 34 suites offer soft-to-the-touch leather furniture, plush and inviting pillow top mattresses,  and the highest level of luxury with newly renovated spa-like bathrooms that include AXENT’s wall-hung AXENT.ONE  intelligent toilets. Inspired by growing popularity for “Japanese toilets,” shower toilets, and bidets, the hotel's management team decided to incorporate the AXENT.ONE intelligent toilet collection into their project due to its unmatched spa-like bathroom features and modern, elegant design. From gentle cleansing, to automatic lid opening and seat warming, theAXENT.ONE offers the most hygienic and comfortable cleansing experience available. The AXENT.ONE’s low-profile and minimalist design lends to the Farmer Hotel Basedow’s unique contemporary yet technology and comfort-driven style.",
    pagelink: "/company/reference/farmer-hotel-basedow",
    category: "HOSITALITY",
    products: ["AXENT.ONE Wall-Mounted Toilet"],
  },
  {
    imgsrc: [
      "/reference_img/haitang-bay-mangrove-resort_1.jpg",
      "/reference_img/haitang-bay-mangrove-resort_2.jpg",
      "/reference_img/haitang-bay-mangrove-resort_3.jpg",
      "/reference_img/haitang-bay-mangrove-resort_4.jpg",
    ],
    title: "Haitang Bay Mangrove Resort",
    location: "Sanya Bay, China",
    description:
      "Haitang Bay Mangrove Resort Hotel - the third in the world, and China's first seven-star resort hotel. With a main building with a top height of 126 meters, gorgeous organic shapes and its location in the heart of Begonia Bay, this new addition to Sanya is quickly becoming a well-deserved new landmark.The hotel features a personal steward service for every room, seven differently themed swimming pools as well as an air bar on the top floor which is the tallest bar in Sanya. AXENT has equipped the Haitang Bay Mangrove Seven Star Resort with state-of-the-art sanitary equipment to make every guest's experience in the bathroom as unique as the rest of this seven-star experience.",
    pagelink: "/company/reference/haitang-bay-mangrove-resort",
    category: "HOSITALITY",
    products: [
      "Athena Intelligent Toilet",
      "Gallia Counter Top Basin",
      "Gallia Wall-hung Urinal",
      "Mag Under Counter Basin",
      "Shelly Recessed Bathtub",
      "Yilia Recessed Bathtub",
      "Marion Counter Top Basin",
    ],
  },
  {
    imgsrc: [
      "/reference_img/bund-financial-center_1.jpg",
      "/reference_img/bund-financial-center_2.jpg",
      "/reference_img/bund-financial-center_3.jpg",
      "/reference_img/bund-financial-center_4.jpg",
      "/reference_img/bund-financial-center_5.jpg",
      "/reference_img/bund-financial-center_6.jpg",
      "/reference_img/bund-financial-center_7.jpg",
      "/reference_img/bund-financial-center_8.jpg",
      "/reference_img/bund-financial-center_9.jpg",
    ],
    title: "Bund Financial Center",
    location: "Shanghai, China",
    description:
      "The Bund Financial Center is a highly prestigious development that occupies a prominent side on the Shanghai Bund. The 420,000-square-metre space with eight buildings called for high-quality sanitaryware, ideally by an internationally renowned brand. Products were required to match harmoniously with the color and tonality of the whole bathroom space. AXENT provided customized services by delivering fitted products according to requirements of the designer, including faucets, push plates, etc., to meet the customer's demands.",
    pagelink: "/company/reference/bund-financial-center",
    category: "HOSITALITY",
    products: [
      "Dean Wall Hung Toilet",
      "Dean Back To Wall Toilet",
      "DuneⅡ1-PC Toilet",
      "Gallia Wall Hung Urinal",
      "Afra Wall Hung Urinal",
      "Toilet Sensor",
      "Wall Mounted Sensor Faucet",
      "Deck Mounted Sensor Faucet",
      "Customized Sensor Faucet",
      "Cristina Deck Mounted Kitchen Faucet",
      "Customized Toilet Sensor",
      "Press Type Delay Faucet",
      "Gene Under Counter Basin",
      "Robe Hook",
    ],
  },
  {
    imgsrc: [
      "/reference_img/ccg-schwarzwald_1.jpg",
      "/reference_img/ccg-schwarzwald_2.jpg",
      "/reference_img/ccg-schwarzwald_3.jpg",
      "/reference_img/ccg-schwarzwald_4.jpg",
      "/reference_img/ccg-schwarzwald_5.jpg",
      "/reference_img/ccg-schwarzwald_6.jpg",
      "/reference_img/ccg-schwarzwald_7.jpg",
      "/reference_img/ccg-schwarzwald_8.jpg",
      "/reference_img/ccg-schwarzwald_9.jpg",
      "/reference_img/ccg-schwarzwald_10.jpg",
      "/reference_img/ccg-schwarzwald_11.jpg",
    ],
    title: "CCG Schwarzwald",
    location: "Shanghai, China",
    description:
      "The CCG Schwarzwald is a high end residential project located in Shanghai. One of the the property development requirements was that all the products should be imported from Germany or comply with German standards. The design style is very minimalistic, focusing on a high product quality and short delivery times. The quality of AXENT meets the German standard. AXENT developed the Dune series proucts and Dean counter top basin specially for the customer.",
    pagelink: "/company/reference/ccg-schwarzwald",
    category: "RESIDENAL",
    products: [
      "Dune series products",
      "Marion Cabinet",
      "Marion Mirror",
      "Dean Counter Top Basin",
    ],
  },
  {
    imgsrc: [
      "/reference_img/nantong-orstar-city_1.jpg",
      "/reference_img/nantong-orstar-city_2.jpg",
    ],
    title: "Nantong Orstar City",
    location: "Nantong, China",
    description:
      "The Nantong Orstar City Phase 2 project is intended to cater to commercial customers and also features modern high end apartments. The sanitary products were required to be inexpensive, user friendly and of a high quality. AXENT provided special product solutions for the project.",
    pagelink: "/company/reference/nantong-orstar-city",
    category: "COMMERCIAL",
    products: [
      "Dora Under Counter Basin",
      "Annie Closed Couple Toilet",
      "Kama Floor Mounted Urinal",
      "Dune Pedestal Basin",
      "Dune Utility Sink",
    ],
  },
  {
    imgsrc: ["/reference_img/zhenru-orstar-city_1.jpg"],
    title: "Zhenru Orstar City",
    location: "Shanghai, China",
    description:
      "Shanghai Zhenru's project Orstar City is a high-end commercial, luxury residential and urban auxiliary project and an important element in promoting the region and enhancing the area's urban function. The developers were looking for global leading design companies Round recessed bathtubs were needed to meet the design requirements. AXENT customized the required products according to the customer request and delivered a customized bathtub.",
    pagelink: "/company/reference/zhenru-orstar-city",
    category: "RESIDENAL",
    products: ["Yilia Recessed Bathtub"],
  },
  {
    imgsrc: [
      "/reference_img/golden-mansion_1.jpg",
      "/reference_img/golden-mansion_2.jpg",
    ],
    title: "Golden Mansion",
    location: "Shanghai, China",
    description:
      "The positioning of this Shanghai residential project is high-end, featuring generous and elegant living spaces. Products were required to reflect a sense of modest luxury, of differentiation and personalization as was requested by the customer. AXENT suggested to make use of its patented I-FLUSH technology to make for a unique user experience. Faucets adopted the golden circle finishing, reflecting the theme of modest luxury present throughout the space.",
    pagelink: "/company/reference/golden-mansion",
    category: "RESIDENAL",
    products: [
      "Allen Intelligent Toilet",
      "Allen Tankless Toilet",
      "Dune 1-pc Toilet",
      "Estrema Under Counter Basin",
      "Cristina Basin Faucet",
      "Dora Under Counter Basin",
      "Julia Recessed Bathtub",
    ],
  },
  {
    imgsrc: [
      "/reference_img/zhuhai-times-port_1.jpg",
      "/reference_img/zhuhai-times-port_2.jpg",
    ],
    title: "Zhuhai Times Port",
    location: "Zhuhai, China",
    description:
      "The Zhuhai Times Port makes every effort to become a regional benchmarking project. Their developer's preference of sanitary ware is a high-end brand and they assign great importance to product quality and an elegant appearance. AXENT recommended and equipped the building with cost-effective products which are simple, beautiful and comfortable.",
    pagelink: "/company/reference/zhuhai-times-port",
    category: "RESIDENAL",
    products: ["Dune Close Coupled Toilet", "Milo Under Counter Basin"],
  },
  {
    imgsrc: ["/reference_img/crape-myrtle-garden_1.jpg"],
    title: "Crape Myrtle Garden",
    location: "Zhejiang, China",
    description:
      "The Crape Myrtle Garden is a relatively high-end full decoration residential project in Taizhou city for which the requirements on the products were very high. Prestigeous European brands provedmost popular among the project's clients, the style was to be simple and short delivery times were required. AXENT products conform with EU quality standards, our Vera Intelligent Seat shines with a with simple and beautiful appearance and humanized design in functions. In addition, it perfectly matches German brand products, winning recognition and praise from both customers and designers.",
    pagelink: "/company/reference/crape-myrtle-garden",
    category: "RESIDENAL",
    products: ["Vera Intelligent Seat"],
  },
  {
    imgsrc: [
      "/reference_img/taskin-city_1.jpg",
      "/reference_img/taskin-city_2.jpg",
      "/reference_img/taskin-city_3.jpg",
      "/reference_img/taskin-city_4.jpg",
      "/reference_img/taskin-city_5.jpg",
    ],
    title: "Taskin City",
    location: "Changsha, China",
    description:
      "Set in a high-end urban context, Taskin City is designed all by international design teams in a simple and straightforward style. The customer required an international sanitary brand which creates products that are innovative, environmentally friendly and energy saving. AXENT's product quality esaily meets the standards set by international brands, we offer trademarked solutions such as A.S.T super water saving technology and S.A.G technology in order to ensure environmental protection and energy efficiency. Also, the minimalistic design style from Italy fots the style of the project prefectly.",
    pagelink: "/company/reference/taskin-city",
    category: "COMMERCIAL",
    products: [
      "Annie Close Coupled Toilet",
      "Dune Wall Hung Toilet",
      "Afra Wall Hung Urinal",
      "Milo Under Counter Basin",
      "Estrema Under Counter Basin",
      "Mark Squat",
    ],
  },
];
